// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start(arg1) {
  return window['go']['scanner']['ScanService']['Start'](arg1);
}

export function Stop(arg1) {
  return window['go']['scanner']['ScanService']['Stop'](arg1);
}