// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {context} from '../models';

export function SetLiveCfgFn(arg1:any):Promise<void>;

export function Start(arg1:scanner.ScanRequest):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop(arg1:string):Promise<void>;
