// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {context} from '../models';

export function OpenNewTerminal(arg1:string):Promise<boolean>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetCaptureManager(arg1:capture.CaptureManager):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteInput(arg1:string,arg2:string):Promise<void>;
