// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['services']['PTYService']['CloseTerminal'](arg1);
}

export function GetWindowsContent(arg1) {
  return window['go']['services']['PTYService']['GetWindowsContent'](arg1);
}

export function OpenNewTerminal(arg1) {
  return window['go']['services']['PTYService']['OpenNewTerminal'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['services']['PTYService']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetCaptureManager(arg1) {
  return window['go']['services']['PTYService']['SetCaptureManager'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['PTYService']['Startup'](arg1);
}

export function WriteInput(arg1, arg2) {
  return window['go']['services']['PTYService']['WriteInput'](arg1, arg2);
}
