// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForgetRemoteHost(arg1) {
  return window['go']['services']['RemoteService']['ForgetRemoteHost'](arg1);
}

export function ListRemoteHosts() {
  return window['go']['services']['RemoteService']['ListRemoteHosts']();
}

export function ListRemoteHostsWithStatus() {
  return window['go']['services']['RemoteService']['ListRemoteHostsWithStatus']();
}

export function RenameRemoteHost(arg1, arg2) {
  return window['go']['services']['RemoteService']['RenameRemoteHost'](arg1, arg2);
}

export function SaveRemoteHost(arg1, arg2, arg3) {
  return window['go']['services']['RemoteService']['SaveRemoteHost'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['services']['RemoteService']['Startup'](arg1);
}

export function TouchRemoteHost(arg1) {
  return window['go']['services']['RemoteService']['TouchRemoteHost'](arg1);
}
