// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function ForgetRemoteHost(arg1:string):Promise<void>;

export function ListRemoteHosts():Promise<Array<config.RemoteHost>>;

export function RenameRemoteHost(arg1:string,arg2:string):Promise<void>;

export function SaveRemoteHost(arg1:config.RemoteHost,arg2:string,arg3:string):Promise<config.RemoteHost>;

export function Startup(arg1:context.Context):Promise<void>;

export function TouchRemoteHost(arg1:string):Promise<void>;
