// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllowedPid(arg1) {
  return window['go']['capture']['CaptureManager']['AddAllowedPid'](arg1);
}

export function ForceCapture() {
  return window['go']['capture']['CaptureManager']['ForceCapture']();
}

export function GetAdapterStatus() {
  return window['go']['capture']['CaptureManager']['GetAdapterStatus']();
}

export function GetWindowsContent(arg1) {
  return window['go']['capture']['CaptureManager']['GetWindowsContent'](arg1);
}

export function RebuildFilterPipeline() {
  return window['go']['capture']['CaptureManager']['RebuildFilterPipeline']();
}

export function RemoveAllowedPid(arg1) {
  return window['go']['capture']['CaptureManager']['RemoveAllowedPid'](arg1);
}

export function Startup(arg1) {
  return window['go']['capture']['CaptureManager']['Startup'](arg1);
}

export function WriteInput(arg1, arg2) {
  return window['go']['capture']['CaptureManager']['WriteInput'](arg1, arg2);
}
